### ISSUE TITLE
display variable as text?

### ISSUE THREAD

**Issue by geronimoooooooo** [kamranahmedse/jquery-toast-plugin#11]
Hi,
Is it possible to display the content of a string variable as text in the toast?

var string_variable = "this is my dynamic text";

$.toast({
  text : " $('string_variable').val()"
}

greetings

**Comment by kamranahmedse** [comment]
Not sure, what you mean by that. But, in your example, you seem to have double quotes around `$('string_variable').val()`. Try
```
$.toast({
    text : $('string_variable').val()
});
```
Or 
```
$.toast($('string_variable').val());
```
