### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by istrau2** [kamranahmedse/jquery-toast-plugin#13]

**Comment by kamranahmedse** [comment]
Added

**Comment by jimnicholls** [comment]
Would it be possible to add a LICENSE.txt along side the README.txt file with a copy of the MIT license? https://opensource.org/licenses/MIT

**Comment by kamranahmedse** [comment]
I don't think there is a need for that. Just a mention in readme is enough.

**Comment by jimnicholls** [comment]
Actually it's not, because of what the license says.

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
