### ISSUE TITLE
toast shows for very less time while using in submit

### ISSUE THREAD

**Issue by wasifnazirmalik** [kamranahmedse/jquery-toast-plugin#17]
Hello I'm a new coder i am using this plugin for form submission whenever the form is submitted the toast appears for a small amount of time and then the page reloads automatically after submit please help
following is my code:
$(document).ready(function(e) {
    
	$("#form").submit(function (e) {
   
    $.toast({
    text: "User Registered",
    heading: 'Admission Successful',
    icon: 'success',
    showHideTransition: 'fade',
	allowToastClose: true,
    hideAfter: false, 
    stack: false, 
    position: 'mid-center', 
    });
	    
    });
   
});

thanks in advance

**Comment by kamranahmedse** [comment]
You can use a mix of toast events and timer to handle that i.e. replace the toast call to this for example

```javascript
e.preventDefault();
// Do your ajax call or whatever
// to register the user

// Show the toast for 5 seconds and then reload/redirect
$.toast({
    text: "User Registered",
    heading: 'Admission Successful',
    icon: 'success',
    showHideTransition: 'fade',
    allowToastClose: true,
    hideAfter: 5000,   // in milli seconds
    beforeHide: function () {
          // do the redirect/reload
    };
})
```
