### ISSUE TITLE
error with fancybox 3

### ISSUE THREAD

**Issue by bolechen** [kamranahmedse/jquery-toast-plugin#28]
when i use jquery.toast with Fancybox 3 (https://github.com/fancyapps/fancybox)
is have error msg in console
`"undefined is not an object (evaluating 'i.opts')"`

debug link: https://codepen.io/bolechen/pen/YxgRvK

**Comment by Tsyklop** [comment]
https://github.com/kamranahmedse/jquery-toast-plugin/issues/29#issuecomment-336656086

**Comment by bolechen** [comment]
Last version if fancybox is fixed this issue.
ref: https://github.com/fancyapps/fancybox/issues/1614
