### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_5_jquery___default.a.toast is not a function

### ISSUE THREAD

**Issue by Minaz123** [kamranahmedse/jquery-toast-plugin#36]
hi,
I am trying to implement this plugin in my reactjs project (in the handleSubmit method). However it throws this type error. could you pls tell me what i might be doing wrong ? 

I am importing it as import $ from 'jquery';  Do i explicitly have to import jquery-toast-plugin ??

**Comment by nilbuild** [comment]
yes you have to import it. Add the below line after you import jquery.

```javascript
import 'jquery-toast-plugin';
```
