### ISSUE TITLE
Width of toast

### ISSUE THREAD

**Issue by codefernandes** [kamranahmedse/jquery-toast-plugin#40]
Hi, exist a way to change de width of a toast ?

If exist, how i can do it ?

Thank´s

**Comment by nilbuild** [comment]
Hey, you can do that applying CSS to `.jq-toast-single`

**Comment by codefernandes** [comment]
Thank´s Kamran !!!

**Comment by sabiland** [comment]
It's actually .jq-toast-wrap class to modify.

**Comment by DhiaDjobbi** [comment]
Yes, you can do that with CSS.
Here is an example:
```
.jq-toast-wrap {
    width:300px;
}
```
