### ISSUE TITLE
$.toast is not a function

### ISSUE THREAD

**Issue by irupeshprasai** [kamranahmedse/jquery-toast-plugin#55]
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/Toast/jquery.toast.min.js"></script>
<link href="~/Scripts/Toast/jquery.toast.min.css" rel="stylesheet" />
<input type="button" id="toast" value="Hello World!!" />
<script>
    $(document).ready(function () {

        $("#toast").on('click', function () {
            $.toast({
                heading: 'Information',
                text: 'Now you can add icons to generate different kinds of toasts',
                showHideTransition: 'slide',
                icon: 'info'
            })
        });
    });

</script>

**Comment by irupeshprasai** [comment]
done

**Comment by ixxxxxx** [comment]
how to solved?
